services:
  backend:
    container_name: lateralthinking-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/lateralthinking/backend
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - lateralthinking-network

  frontend:
    container_name: lateralthinking-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/lateralthinking/frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    command: npm start
    
    networks:
      - lateralthinking-network

  postgres:
    container_name: lateralthinking-postgres
    image: postgres
    env_file:
      - ./backend/var.env
    volumes:
       - postgres:/data/postgres
       - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - lateralthinking-network

networks:
  lateralthinking-network:

volumes:
  postgres: