services:
  # do nothing
  backend:
    build: .devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done" # does nothing, otherwise a webserver instance will be spawned when opening with devcontainer
    volumes:
      - ./:/lateralthinking
    environment:
      IS_LOCAL: True
    networks:
     - lateralthinking-network
  
  pgadmin:
    container_name: lateralthinking-pgadmin_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - lateralthinking-network

networks:
  lateralthinking-network: