services:
  # do nothing
  backend:
    build: .devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done" # does nothing, otherwise a webserver instance will be spawned when opening with devcontainer
    volumes:
      - ./:/lateralthinking
    environment:
      IS_LOCAL: True
    ports:
      - "3000:3000"
      - "8001:8001"
    networks:
     - lateralthinking-network
  
  pgadmin:
    container_name: lateralthinking-pgadmin_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - lateralthinking-network

  frontend:
    container_name: lateralthinking-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/lateralthinking/frontend
    depends_on:
      backend:
        condition: service_started
    
    networks:
      - lateralthinking-network

  postgres:
    container_name: lateralthinking-postgres
    image: postgres
    env_file:
      - ./backend/var.env
    volumes:
       - postgres:/data/postgres
       - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - lateralthinking-network

volumes:
  postgres:

networks:
  lateralthinking-network: